from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class DMessage(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> DMessage: ...
  @classmethod
  def GetRootAsDMessage(cls, buf: bytes, offset: int) -> DMessage: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Text(self) -> str | None: ...
def DMessageStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def DMessageAddText(builder: flatbuffers.Builder, text: uoffset) -> None: ...
def DMessageEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

