# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class DRSA(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DRSA()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDRSA(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DRSA
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DRSA
    def P(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # DRSA
    def Q(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def DRSAStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    DRSAStart(builder)

def DRSAAddP(builder: flatbuffers.Builder, p: int):
    builder.PrependInt64Slot(0, p, 0)

def AddP(builder: flatbuffers.Builder, p: int):
    DRSAAddP(builder, p)

def DRSAAddQ(builder: flatbuffers.Builder, q: int):
    builder.PrependInt64Slot(1, q, 0)

def AddQ(builder: flatbuffers.Builder, q: int):
    DRSAAddQ(builder, q)

def DRSAEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DRSAEnd(builder)
