from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class DRSA(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> DRSA: ...
  @classmethod
  def GetRootAsDRSA(cls, buf: bytes, offset: int) -> DRSA: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def P(self) -> int: ...
  def Q(self) -> int: ...
def DRSAStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def DRSAAddP(builder: flatbuffers.Builder, p: int) -> None: ...
def DRSAAddQ(builder: flatbuffers.Builder, q: int) -> None: ...
def DRSAEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

